# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluent-plugin-td}
  s.version = "0.9.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sadayuki Furuhashi"]
  s.date = %q{2011-09-07}
  s.extra_rdoc_files = [
    "ChangeLog",
     "README.rdoc"
  ]
  s.files = [
    "AUTHORS",
     "Rakefile",
     "VERSION",
     "example.conf",
     "fluent-plugin-td.gemspec",
     "lib/fluent/plugin/out_tdlog.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Treasure Data plugin for Fluent event collector}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fluent>, ["~> 0.9.9"])
      s.add_runtime_dependency(%q<td-client>, ["~> 0.8.0"])
    else
      s.add_dependency(%q<fluent>, ["~> 0.9.9"])
      s.add_dependency(%q<td-client>, ["~> 0.8.0"])
    end
  else
    s.add_dependency(%q<fluent>, ["~> 0.9.9"])
    s.add_dependency(%q<td-client>, ["~> 0.8.0"])
  end
end

