version: 2.1
orbs:
  ruby: circleci/ruby@1.8
jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake test
  publish:
    docker:
      - image: cimg/ruby:2.4
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Publish gem
          command: |
            mkdir -p $HOME/.gem
            touch $HOME/.gem/credentials
            chmod 0600 $HOME/.gem/credentials
            printf -- "---\n:rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}\n" > $HOME/.gem/credentials
            gem build *.gemspec
            gem push *.gem
workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: [ "2.4", "2.5", "2.6", "2.7", "3.0", "3.1" ]
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          context: rubygems
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/